### ISSUE TITLE
Release of NTRUEncrypt to Public Domain

### ISSUE THREAD

**Issue by tristanhoy** [cyph/ntru.js#1]
As per media release: https://globenewswire.com/news-release/2017/03/28/945815/0/en/Security-Innovation-Makes-NTRUEncrypt-Patent-Free.html

There is a specific "Public Domain" release of NTRUEncrypt here: https://github.com/NTRUOpenSourceProject/NTRUEncrypt/releases/tag/Public-domain

Which implements the following released patents:
https://github.com/NTRUOpenSourceProject/NTRUEncrypt/blob/master/PATENTS 

However, your README.MD links to a different project implementing patents that are not covered by the Public Domain release (including signatures), which makes the patent/licensing status of your module unclear:
https://github.com/NTRUOpenSourceProject/ntru-crypto/blob/master/PATENTS.md

Do you have any plans to target the Public Domain NTRUEncrypt release?

**Comment by buu700** [comment]
Nice, that's great news! The main NTRUEncrypt implementation that we're cross-compiling here is the same one that you linked (the `Public-domain` tag is in the same repository), but to remove all doubt I'll re-make ntru.js with the latest master of NTRUEncrypt and replace the link you noted in the readme with a link to the Wikipedia page.
