### ISSUE TITLE
NTRU generally shouldn't be used to directly encrypt your data?

### ISSUE THREAD

**Issue by lakano** [cyph/ntru.js#2]
Hi !

You wrote: « NTRU generally shouldn't be used to directly encrypt your data; in most cases, you'll want to pair it with a symmetric cipher and use it to encrypt symmetric keys. »

I'm not sure to understood the reason? 

For example, It's not recommended to use a NTRU key pair to encrypt data sent from a client to a server?

Regards,

**Comment by buu700** [comment]
That should be worded more clearly, but what I meant is that this module doesn't provide a high-level construct like, say, libsodium's [crypto_box](https://download.libsodium.org/doc/public-key_cryptography/authenticated_encryption.html). What this module is providing is a low-level cryptographic primitive, which could be used to build such a construct if it were combined with a symmetric cipher and a MAC.

The most obvious limitation of this if you start to play around with it is you'll find that it can't directly encrypt any data larger than 106 bytes, e.g. `await ntru.encrypt(new Uint8Array(107), (await ntru.keyPair()).publicKey)` fails with `Error: Plaintext length exceeds ntru.plaintextBytes.`.

**Comment by lakano** [comment]
Thank you @buu700 for your feedback. Is it a limitation of the NTRU C library or a limitation caused by the WebAssembly port to JavaScript please?

Even for sending a symmetric key, 106 bytes (848 bits) isn't very much, may be we need to generate multiple keys pair to send multiples parts of the symmetric key if we want for example a 4096 bits key?

**Comment by buu700** [comment]
That's a limitation inherited from the C library. 106 bytes is quite a lot for encrypting a symmetric key; I'm not sure there's any real-world use case for keys larger than 256 or 512 bits. If you do need to use larger symmetric keys, I suppose you could design a construct that uses multiple NTRU-encrypted messages.

**Comment by lakano** [comment]
Thank you @buu700 for your explanations 👍

**Comment by buu700** [comment]
Sure, not a problem at all.
