### ISSUE TITLE
Max length (or block support)

### ISSUE THREAD

**Issue by svanschooten** [cyph/ntru.js#4]
At the moment the longest string I can put into the encryption is 106, which is not really useful.
Maybe add support for block encoding/decoding? Since the cipher length varies a bit, padding with zero bytes to max length should be possible.

Along with [PR#3](https://github.com/cyph/ntru.js/pull/3) implementing cipher block chaining can be done.

**Comment by buu700** [comment]
Hey, sorry, meant to read this a lot sooner. The intent of this module is only to wrap the NTRU C library, which as you've noticed is barebones and provides nothing beyond the NTRU cipher itself. Additional functionality like you're describing would be straightforward to handle in a higher-level library.

As far as PR #3, it's unfinished and probably abandoned, but I'd be happy to accept it if someone else took over and finished it.

**Comment by svanschooten** [comment]
I can imagine, but using this library in combination with a Java server is not working for me (BouncyCastle implementation), even when using the same parameter presets. I'm hoping wrapping the C project in a Java interface will provide me with a better result, as it should have to work the same as this wrapper. Do you have any experience with that?

**Comment by buu700** [comment]
Unfortunately I don't, but I don't see any reason why it wouldn't work if the parameters are exactly the same. Is Bouncy Castle maybe providing a higher-level API that doesn't have the 106 length limitation? If that is the case, you would need to implement the exact same scheme on the JS end.

In any case, wrapping the C library for Java sounds worth trying; let me know how it goes! If it's less work, I would also try out [tbuktu/ntru](https://github.com/tbuktu/ntru).

**Comment by svanschooten** [comment]
Ugh, this is my first time working with self written JNI code, and can't get it working so far (undefined symbol: ntru_crypto_drbg_instantiate) and I can't figure out how to link these libraries to be portable...

BouncyCastle uses a different limit, its 185 for them. The do not provide a very high level api, but it weirds me out that the key generated in JS cannot be used in Java and vice versa. The problem with the tbuktu implementation is that it is the same implementation as BC (BC forks it into their build tree).

I'm kinda lost, since we need a PQS key exchange method between a browser and Java application....

**Comment by buu700** [comment]
Hmm, are you sure you're definitely using the same parameter set? Based on [ntru_crypto_ntru_encrypt_param_sets.c#L228](https://github.com/NTRUOpenSourceProject/NTRUEncrypt/blob/89aa2ad/src/ntru_crypto_ntru_encrypt_param_sets.c#L228), that limit would make sense for EES1171EP1, whereas ntru.js uses EES743EP1.

**Comment by svanschooten** [comment]
Uh yeah, I recompiled it a few times to try different parameter sets (and set the corresponding parameter sets in BC) if any of them would work. I guess the problem is with reconstructing the keys, since the encoded version of the key differs from the imported one, but when I reconstruct an exported key from BC itself it does actually work.

Also tried the other way around, but that also does not work...
@buu700 Many thanks for thinking along with me! Though I think I will give up on the (in my opinion) nicest asymmetrical cipher NTRU, I'll be looking at the NewHope key exchange method to see if that will work.

**Comment by buu700** [comment]
Well that's pretty odd, but good luck!
